version: "3.7"
services:
  app:
      build:
        args:
          user: aji
          uid: 1000
        context: ./
        dockerfile: ./Dockerfile
      image: doorprice
      container_name: doorprice-app
      working_dir: /var/www/
      volumes:
        - ./:/var/www
        - ./user.ini:/usr/local/etc/php/php.ini
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
      networks:
        - doorprice
  nginx:
    image: nginx:1.17-alpine
    container_name: doorprice-nginx
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - doorprice
  nodejs:
    image: node:16-alpine
    container_name: doorprice-node
    ports:
      - 5173:5173
    volumes:
      - ./:/var/www
    working_dir: /var/www
    entrypoint: ["npm","run", "dev"]
    networks:
      - doorprice

networks:
  doorprice:
    driver: bridge
    ipam:
      driver: default
      config:
          - subnet: 10.99.99.0/24
            gateway: 10.99.99.1
